name: Nightly Build and Push

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every night at 12 AM UTC
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Run Tests
      - name: Run Tests
        run: |
          docker compose down
          docker compose up -d --build
          sleep 10  # Wait for services to start
          docker exec fastapi-beyond-crud-web-1 pytest src/tests/
          docker compose down

      # Build Docker Image
      - name: Build Docker Image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest .

      # Push Docker Image to Registry
      - name: Push Docker Image to Registry
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

      # Install msmtp for email notifications
      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp-mta

      # Send Failure Email Notification
      - name: Send Failure Email Notification
        if: failure()
        run: |
          echo "Subject: Nightly Build Failed" > email.txt
          echo "" >> email.txt
          echo "The nightly build and test process has failed." >> email.txt
          echo "Please check the logs for more details." >> email.txt
          
          msmtp -a default -t <<EOF
          To: recipient@no-reply-github.com
          From: ${{ secrets.SMTP_USER }}
          Subject: Nightly Build Failure

          $(cat email.txt)
          EOF
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
